name: Bump Poetry Version
description: Bumps the poetry version based on the release type and creates a new git tag.
inputs:
  releaseType:
    description: 'The type of release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Bump poetry version
      shell: bash
      run: |
        poetry version "${{ inputs.releaseType }}"
        latest_image_version=$(poetry version --short)
        echo "LATEST_IMAGE_VERSION=$latest_image_version" >> $GITHUB_ENV
        cli_tag_version="cli-${latest_image_version}"

        # Add commit messsage for message bump
        git add .
        git commit -m "Bump poetry version to $latest_image_version"

        # Check if the new version tag already exists
        if git rev-parse "$cli_tag_version" >/dev/null 2>&1; then
          echo "Tag $cli_tag_version already exists."
        else
          # Commit and tag the new version
          echo "Tag $cli_tag_version does not exist."
          git tag -a $cli_tag_version -m "$cli_tag_version"
          git show "$cli_tag_version"
        fi
