name: Mantis CLI Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
        releaseType:
          description: 'What kind of release is this?'
          required: true
          type: choice
          options:
            - 'major'
            - 'minor'
            - 'patch'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ncoder2/ncoder2mantis

jobs:
  build-and-push-image:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install generate-changelog bump-my-version

      - name: Generate the changelog and get the release hint
        id: generate-changelog
        run: |
          RELEASE_KIND=$(generate-changelog --output release-hint)
          echo "::notice::Suggested release type for this branch is: ${RELEASE_KIND}"
          echo "RELEASE_KIND=$RELEASE_KIND" >> $GITHUB_ENV
          echo "release-kind=$RELEASE_KIND" >> $GITHUB_OUTPUT
          echo "PACKAGE=false" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
              bump-my-version bump --allow-dirty --verbose "$RELEASE_KIND"
              echo "TAG_NAME=$(bump-my-version show current_version)" >> $GITHUB_ENV
              git push
              git push --tags
              echo "PACKAGE=true" >> $GITHUB_ENV
          
      - name: Push version bump commit and tag
        run: |
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.bump_version.outputs.new_version }}
          labels: ${{ steps.meta.outputs.labels }}
